CREATE INDEX "article_likes_article_id_idx" ON "article_likes" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "article_likes_article_id_visitor_id_idx" ON "article_likes" USING btree ("article_id","visitor_id");--> statement-breakpoint
CREATE INDEX "article_views_article_id_idx" ON "article_views" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "articles_author_id_idx" ON "articles" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "articles_is_draft_idx" ON "articles" USING btree ("is_draft");--> statement-breakpoint
CREATE INDEX "articles_created_at_idx" ON "articles" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "articles_is_draft_created_at_idx" ON "articles" USING btree ("is_draft","created_at");--> statement-breakpoint
CREATE INDEX "comment_reactions_comment_id_idx" ON "comment_reactions" USING btree ("comment_id");--> statement-breakpoint
CREATE INDEX "comment_reactions_user_id_idx" ON "comment_reactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "comments_article_id_idx" ON "comments" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "comments_user_id_idx" ON "comments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "comments_parent_id_idx" ON "comments" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "experience_type_idx" ON "experience" USING btree ("type");--> statement-breakpoint
CREATE INDEX "experience_is_draft_idx" ON "experience" USING btree ("is_draft");--> statement-breakpoint
CREATE INDEX "experience_start_date_idx" ON "experience" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "experience_created_at_idx" ON "experience" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "experience_type_is_draft_idx" ON "experience" USING btree ("type","is_draft");--> statement-breakpoint
CREATE INDEX "guestbook_user_id_idx" ON "guestbook" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "guestbook_created_at_idx" ON "guestbook" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "project_is_draft_idx" ON "project" USING btree ("is_draft");--> statement-breakpoint
CREATE INDEX "project_is_featured_idx" ON "project" USING btree ("is_featured");--> statement-breakpoint
CREATE INDEX "project_created_at_idx" ON "project" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "project_is_draft_is_featured_idx" ON "project" USING btree ("is_draft","is_featured");--> statement-breakpoint
CREATE INDEX "service_is_draft_idx" ON "service" USING btree ("is_draft");--> statement-breakpoint
CREATE INDEX "service_created_at_idx" ON "service" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "snippet_category_idx" ON "snippet" USING btree ("category");--> statement-breakpoint
CREATE INDEX "snippet_is_draft_idx" ON "snippet" USING btree ("is_draft");--> statement-breakpoint
CREATE INDEX "snippet_created_at_idx" ON "snippet" USING btree ("created_at");